thread-mode: virtual

spring:

  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:6000/postgres?currentSchema=library
    platform: postgres
    password: postgres

server:
  port: '8081'
