spring:
  threads:
    virtual:
      enabled: ${VIRTUAL_THREAD_ENABLED:true}

  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=library&user=postgres&password=postgres}
    hikari:
      maximum-pool-size: ${HIKARICP_CONNECTION_POOL:15}

  jpa:
    generate-ddl: 'false'
    database: POSTGRESQL
    properties:
      hibernate:
        default_schema: library
    show-sql: 'false'
    hibernate:
      ddl-auto: none

server:
  port: ${SERVER_PORT:8081}
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus
    health:
      show-details: always
  metrics:
    tags:
      application: spring-boot-virtual-threads