package gae.piaz.boot.virtual.repository;

import jakarta.transaction.Transactional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import gae.piaz.boot.virtual.domain.Book;

/**
 * Generated by Springboot-3layer-Generator at Jan 6, 2021, 8:30:41 PM
 */
@Repository
public interface BookRepository extends JpaRepository<Book, Integer> {

    Book findByIsbn(String isbn);

    @Transactional
    @Query("DELETE FROM Book e WHERE e.id <> :idToKeep")
    @Modifying
    void deleteAllBut(@Param("idToKeep") Integer idToKeep);
}