package gae.piaz.boot.virtual.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import gae.piaz.boot.virtual.domain.User;

/**
 * Generated by Springboot-3layer-Generator at Jan 6, 2021, 8:30:41 PM
 */
@Repository
public interface UserRepository extends JpaRepository<User, Integer> {

    User findByFirstName(String firstName);
}